name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make install
    
    - name: Lint
      run: make lint
    
    - name: Test
      run: make test
      
    - name: Format
      run: make format
      
    - name: Run distcheck
      run: make distcheck
